server.name: benchmark-cluster
server.port: 8095

api.timeout-ms: 5000

exchange:
  grpc:
    hosts: localhost,localhost,localhost
    ports: 9500,9501,9502

spring:
  threads:
    virtual:
      enabled: true

management:
  opentelemetry:
    resource-attributes:
      "service.name": ${server.name}
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always
      show-details: always
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 5s
  metrics:
    tags:
      service: ${server.name}
      instance.id: ${random.long(1000,9999)}
