server.name: benchmark-cluster
server.port: 8095

api.timeout-ms: 5000

exchange:
  grpc:
    hosts: localhost,localhost,localhost
    ports: 9500,9501,9502

spring:
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
